<?php

/**
 * JobeetCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class JobeetCategory extends BaseJobeetCategory{

	public function getWithJobs()
  {
    $q = $this->createQuery('c')
      ->leftJoin('c.JobeetJobs j')
      ->where('j.expires_at > ?', date('Y-m-d h:i:s', time()));
 
    return $q->execute();
  }

	public function getActiveJobs($max = 10){
		$q = Doctrine_Query::create()
			->from('JobeetJob j')
			->where('j.category_id = ?', $this->getId())
			->limit($max);
 
		return Doctrine_Core::getTable('JobeetJob')->getActiveJobs($q);
	}

	public function getSlug(){
		return Jobeet::slugify($this->getName());
	}

	public function countActiveJobs(){
		$q = Doctrine_Query::create()
			->from('JobeetJob j')
			->where('j.category_id = ?', $this->getId());

		return Doctrine_Core::getTable('JobeetJob')->countActiveJobs($q);
	}

	public function getActiveJobsQuery(){
		$q = Doctrine_Query::create()
			->from('JobeetJob j')
			->where('j.category_id = ?', $this->getId());

		return Doctrine_Core::getTable('JobeetJob')->addActiveJobsQuery($q);
	}

}
