category:
  url: /category/:slug
  class: sfDoctrineRoute
  options: { model: JobeetCategory, type: object }
  param: { module: category, action: show }

job:
  class: sfDoctrineRouteCollection
  options: { model: JobeetJob }
  
job_show_user:
  url:   /job/:company_slug/:location_slug/:id/:position_slug
  class: sfDoctrineRoute
  options: { model: JobeetJob, type: object }
  param: { module: job, action: show }
  requirements:
     id: \d+
     sf_method: [get]

homepage:
  url:   /
  param: { module: job, action: index }

#default_index:
#  url:   /:module
#  param: { action: index }

#default:
#  url:   /:module/:action/*
