<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/14 11:22:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'jobeet',
  'password' => 'jobeet',
  'name' => 'doctrine',
)),);
